### ISSUE TITLE
Hyper-V provisioning fails in 1.8.0: Error getting host adapter ip address: No ip address.

### ISSUE THREAD

**Issue by hc-github-team-packer** [hashicorp/packer-plugin-hyperv#65]
_This issue was originally opened by @voltagex in https://github.com/hashicorp/packer/issues/11794 and has been migrated to this repository. The original issue description is below._

---

#### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

When filing a bug, please include the following headings if possible. Any
example text in this template can be deleted.

#### Overview of the Issue

Packer 1.8.0 fails to get the Hyper-V host IP
Packer 1.7.10 works 'correctly' - although this is only one of the machine's IPs.

#### Reproduction Steps

Steps to reproduce this issue

Build the packer file below.
Error.

### Packer version
Packer v1.8.0 and
Packer v1.7.10

### Simplified Packer Template

```hcl
source "hyperv-iso" "autogenerated_1" {
  boot_wait = "1s"
  boot_command = [
  "<esc><wait5><esc><esc><enter><wait>",
  "set gfxpayload=keep<enter>",
  "linux /casper/vmlinuz ",
  "noprompt autoinstall 'ds=nocloud-net;s=http://10.0.0.144:8000/' --- <enter>",
  "initrd /casper/initrd<enter>",
  "boot<enter>"]

  communicator         = "ssh"
  cpus                 = "4"
  disk_size            = "20000"
  enable_secure_boot   = false
  generation           = 2
  guest_additions_mode = "disable"
  http_directory       = "./local-testing/"
  iso_checksum         = "file:https://mirror.aarnet.edu.au/pub/ubuntu/releases/20.04.4/SHA256SUMS"
  iso_url              = "http://mirror.aarnet.edu.au/pub/ubuntu/releases/20.04.4/ubuntu-20.04.4-live-server-amd64.iso"
  memory               = "4096"
  shutdown_command     = "echo 'packer' | sudo -S -E shutdown -P now"
  ssh_password         = "packer"
  ssh_timeout          = "4h"
  ssh_username         = "packer"
  vm_name              = "bug-test"
}

build {
  sources = ["source.hyperv-iso.autogenerated_1"]
}

```
### Operating system and Environment details

Brand new Windows 11 install. Haven't tested this on Windows 10.

OS, Architecture, and any other information you can provide about the
environment.

### Log Fragments and crash.log files

1.7.10
```
PS C:\temp> packer-1.7.10.exe build .\zz_local_testing.pkr.hcl
hyperv-iso.autogenerated_1: output will be in this color.                                                                                                                                                                                       ==> hyperv-iso.autogenerated_1: Creating build directory...                                                             ==> hyperv-iso.autogenerated_1: Retrieving ISO                                                                          ==> hyperv-iso.autogenerated_1: Trying http://mirror.aarnet.edu.au/pub/ubuntu/releases/20.04.4/ubuntu-20.04.4-live-server-amd64.iso                                                                                                             ==> hyperv-iso.autogenerated_1: Trying http://mirror.aarnet.edu.au/pub/ubuntu/releases/20.04.4/ubuntu-20.04.4-live-server-amd64.iso?checksum=sha256%3A28ccdb56450e643bad03bb7bcf7507ce3d8d90e8bf09e38f6bd9ac298a98eaad                          ==> hyperv-iso.autogenerated_1: http://mirror.aarnet.edu.au/pub/ubuntu/releases/20.04.4/ubuntu-20.04.4-live-server-amd64.iso?checksum=sha256%3A28ccdb56450e643bad03bb7bcf7507ce3d8d90e8bf09e38f6bd9ac298a98eaad => C:\temp\packer_cache\47de2d7266acde194681de2a24f5d76b43b452ca.iso
==> hyperv-iso.autogenerated_1: Starting HTTP server on port 8592
==> hyperv-iso.autogenerated_1: Creating switch 'packer-autogenerated_1' if required...
==> hyperv-iso.autogenerated_1:     switch 'packer-autogenerated_1' already exists. Will not delete on cleanup...
==> hyperv-iso.autogenerated_1: Creating virtual machine...
==> hyperv-iso.autogenerated_1: Enabling Integration Service...
==> hyperv-iso.autogenerated_1: Setting boot drive to os dvd drive C:\temp\packer_cache\47de2d7266acde194681de2a24f5d76b43b452ca.iso ...
==> hyperv-iso.autogenerated_1: Mounting os dvd drive C:\temp\packer_cache\47de2d7266acde194681de2a24f5d76b43b452ca.iso ...
==> hyperv-iso.autogenerated_1: Skipping mounting Integration Services Setup Disk...
==> hyperv-iso.autogenerated_1: Mounting secondary DVD images...
==> hyperv-iso.autogenerated_1: Configuring vlan...
==> hyperv-iso.autogenerated_1: Determine Host IP for HyperV machine...
==> hyperv-iso.autogenerated_1: Host IP for the HyperV machine: 169.254.189.124
==> hyperv-iso.autogenerated_1: Attempting to connect with vmconnect...
==> hyperv-iso.autogenerated_1: Starting the virtual machine...
==> hyperv-iso.autogenerated_1: Waiting 1s for boot...
==> hyperv-iso.autogenerated_1: Typing the boot command...
Cancelling build after receiving interrupt
==> hyperv-iso.autogenerated_1: Error running boot command: context canceled
==> hyperv-iso.autogenerated_1: Disconnecting from vmconnect...
==> hyperv-iso.autogenerated_1: Clean up os dvd drive...
==> hyperv-iso.autogenerated_1: Unregistering and deleting virtual machine...
==> hyperv-iso.autogenerated_1: Deleting output directory...
==> hyperv-iso.autogenerated_1: Deleting build directory...
Build 'hyperv-iso.autogenerated_1' errored after 20 seconds 785 milliseconds: Error running boot command: context canceled

==> Wait completed after 20 seconds 785 milliseconds
Cleanly cancelled builds after being interrupted.
PS C:\temp>

```
(error is expected, I cancelled once it got to the grub boot screen)

1.8.0:

```
PS C:\temp> packer build .\zz_local_testing.pkr.hcl
hyperv-iso.autogenerated_1: output will be in this color.

==> hyperv-iso.autogenerated_1: Creating build directory...
==> hyperv-iso.autogenerated_1: Retrieving ISO
==> hyperv-iso.autogenerated_1: Trying http://mirror.aarnet.edu.au/pub/ubuntu/releases/20.04.4/ubuntu-20.04.4-live-server-amd64.iso
==> hyperv-iso.autogenerated_1: Trying http://mirror.aarnet.edu.au/pub/ubuntu/releases/20.04.4/ubuntu-20.04.4-live-server-amd64.iso?checksum=sha256%3A28ccdb56450e643bad03bb7bcf7507ce3d8d90e8bf09e38f6bd9ac298a98eaad
==> hyperv-iso.autogenerated_1: http://mirror.aarnet.edu.au/pub/ubuntu/releases/20.04.4/ubuntu-20.04.4-live-server-amd64.iso?checksum=sha256%3A28ccdb56450e643bad03bb7bcf7507ce3d8d90e8bf09e38f6bd9ac298a98eaad => C:\temp\packer_cache\47de2d7266acde194681de2a24f5d76b43b452ca.iso
==> hyperv-iso.autogenerated_1: Starting HTTP server on port 8845
==> hyperv-iso.autogenerated_1: Creating switch 'packer-autogenerated_1' if required...
==> hyperv-iso.autogenerated_1:     switch 'packer-autogenerated_1' already exists. Will not delete on cleanup...
==> hyperv-iso.autogenerated_1: Creating virtual machine...
==> hyperv-iso.autogenerated_1: Enabling Integration Service...
==> hyperv-iso.autogenerated_1: Setting boot drive to os dvd drive C:\temp\packer_cache\47de2d7266acde194681de2a24f5d76b43b452ca.iso ...
==> hyperv-iso.autogenerated_1: Mounting os dvd drive C:\temp\packer_cache\47de2d7266acde194681de2a24f5d76b43b452ca.iso ...
==> hyperv-iso.autogenerated_1: Skipping mounting Integration Services Setup Disk...
==> hyperv-iso.autogenerated_1: Mounting secondary DVD images...
==> hyperv-iso.autogenerated_1: Configuring vlan...
==> hyperv-iso.autogenerated_1: Determine Host IP for HyperV machine...
==> hyperv-iso.autogenerated_1: Error getting host adapter ip address: No ip address.
==> hyperv-iso.autogenerated_1: Clean up os dvd drive...
==> hyperv-iso.autogenerated_1: Unregistering and deleting virtual machine...
==> hyperv-iso.autogenerated_1: Deleting output directory...
==> hyperv-iso.autogenerated_1: Deleting build directory...
Build 'hyperv-iso.autogenerated_1' errored after 12 seconds 487 milliseconds: Error getting host adapter ip address: No ip address.

==> Wait completed after 12 seconds 487 milliseconds

==> Some builds didn't complete successfully and had errors:
--> hyperv-iso.autogenerated_1: Error getting host adapter ip address: No ip address.

==> Builds finished but no artifacts were created.
```

[packer-1.7.log](https://github.com/hashicorp/packer/files/8721854/packer-1.7.log)

[packer-1.8.log](https://github.com/hashicorp/packer/files/8721856/packer-1.8.log)

**Comment by bendem** [comment]
Can confirm this happens on Windows 10 as well. I find those lines in the logs weird :

```
==> hyperv-iso.rocky: Creating switch 'packer-rocky' if required...
==> hyperv-iso.rocky:     switch 'packer-rocky' already exists. Will not delete on cleanup...
```

The switch is created by packer but packer seems to think it didn't do it, maybe it means the switch is also not getting configured correctly?

**Comment by zmance-ddn** [comment]
@alexander-rabenstein did you configure anything else on your hyper-v host to get this working? I downgraded to 1.7.10 and I am still having issue. I feel like I'm fighting the virtual switch.

**Comment by alexander-rabenstein** [comment]
> @alexander-rabenstein did you configure anything else on your hyper-v host to get this working? I downgraded to 1.7.10 and I am still having issue. I feel like I'm fighting the virtual switch.

No not that I can remember!

**Comment by bendem** [comment]
According to the commits applied between 1.7 and 1.8, this is the culprit. I have not yet tried to reproduce the problem with this change reverted.
https://github.com/hashicorp/packer-plugin-hyperv/commit/1795335a489e823e09d7ec5b03f7dac5e24baf6f

**Comment by devmuppet** [comment]
> Thanks, downgrade packer from 1.8.3 to 1.7.0 works for me too.

choco downgrade to 1.7.3 works a treat for me!

**Comment by cmf1541** [comment]
> @alexander-rabenstein did you configure anything else on your hyper-v host to get this working? I downgraded to 1.7.10 and I am still having issue. I feel like I'm fighting the virtual switch.

I had the same problem due to packer using the external Hyper-V plugin rather than the one built into 1.7.10. Setting the required_plugins block as below fixed it for me. Was also able to get packer 1.8.2 working as well by doing this.
```
packer {
  required_plugins {
    hyperv = {
      version = "= 1.0.1"
      source  = "github.com/hashicorp/hyperv"
    }
  }
}
```

**Comment by nywilken** [comment]
Folks thanks for updating this thread with your finds. I'm marked this as a regression so that we can take a look and see what might be going on. @bendem seeing as you are looking at the code. If you have a handle on the issue and would like to open a PR we would be happy to review. 

That said, with the plugins being separated from Packer versions of the plugin can be installed without having to downgrade Packer as @cmf1541 is calling out. For context, this plugin along with most of the other HashiCorp Packer Plugin repos are currently bundled into the Packer binary for backwards compatibility reasons. But folks, if they haven't already, are encouraged to pin the  required plugins via `packer init` or the `packer plugins` command. It will help protect exactly against these types of regressions and provide a mechanism for testing new versions of the plugins before upgrading.


For folks using HCL2 templates the recommended approach for installing plugins like this one is to use the required_plugins block. I'm duplicating @cmf1541 code snippet to help illustrate the usage. Running `packer init .` in the template directory will install and force Packer to use defined version in the required_plugins block. 

```hcl
packer {
  required_plugins {
    hyperv = {
      version = "= 1.0.1"
      source  = "github.com/hashicorp/hyperv"
    }
  }
}
```

If folks here are using JSON templates the `packer init` command will not work for you. But we do have an alternative approach. The `packer plugins install` command allows you to external plugins at any specific version. If no version is specified the latest version will get downloaded and installed. The command below will install the specified version of the Hyper-V plugin, which Packer will use automatically at runtime. 

```bash
packer plugins install github.com/hashicorp/hyperv "=1.0.1"
```


I should mention that plugins in the required_plugins block take precedence over any plugin already installed on the system.

**Comment by revtex** [comment]
So, I wasn't having any issues until I upgraded Windows 11 to 22H2.  After that, I started getting the **"Error getting host adapter ip address: No ip address."** error.  Setting required_plugins as listed above did get it past that error as long as packer creates the vswitch.  If the switch_name is set to **"Default Switch"** I get the error again. But now that I rolled back to an older version of the Hyper-V plugin the VM it creates will no longer boot (may be a separate issue).

**Comment by alexander-rabenstein** [comment]
> 

Thx for the feedback, didnt see the information somewhere in the documentation. Also how should a enduser know which versions of the plugins are available. Documentation should be updated.

**Comment by bendem** [comment]
> @bendem seeing as you are looking at the code. If you have a handle on the issue and would like to open a PR we would be happy to review.

That commit was a fix for W11, I only have W10 to test and I'm unsure how to modify those scripts for testing. The fix would probably be to fall back to the previous WMI check if the new method doesn't work. Now why it doesn't work, that's a good question, I'm not familiar enough with hyper-v powershell to know.

**Comment by DimeOne** [comment]
Packer 1.8.3 with hyperv-iso 1.0.4 is reporting the same problem with Windws 11 22H2.

However the issue seems to be different.

[1] PowerShell Get-NetAdapter does not show Default Switch Interface by default
I have taken a look a the powershell script to getrieve the ip address and simplified it:
`Get-NetAdapter | Where-Object DeviceId -in (Hyper-V\Get-VMNetworkAdapter -ManagementOS | Select-Object -ExpandProperty DeviceId)`

The following should return all ipv4 profiles belonging to the default switch, but does not return anything for me. instead I have to use the -IncludeHidden switch:
`Get-NetAdapter -IncludeHidden | Where-Object DeviceId -in (Hyper-V\Get-VMNetworkAdapter -ManagementOS -SwitchName "Default Switch" | Select-Object -ExpandProperty DeviceId) | Get-NetIPAddress -AddressFamily IPv4
`

Then again, unsure if it is because of wsl installed, that query returns 2 profiles:

```
IPAddress         : 172.30.80.1
InterfaceIndex    : 18
InterfaceAlias    : vEthernet (nat)
AddressFamily     : IPv4
Type              : Unicast
PrefixLength      : 20
PrefixOrigin      : Manual
SuffixOrigin      : Manual
AddressState      : Preferred
ValidLifetime     : Infinite ([TimeSpan]::MaxValue)
PreferredLifetime : Infinite ([TimeSpan]::MaxValue)
SkipAsSource      : False
PolicyStore       : ActiveStore

IPAddress         : 172.25.208.1
InterfaceIndex    : 34
InterfaceAlias    : vEthernet (Default Switch)
AddressFamily     : IPv4
Type              : Unicast
PrefixLength      : 20
PrefixOrigin      : Manual
SuffixOrigin      : Manual
AddressState      : Preferred
ValidLifetime     : Infinite ([TimeSpan]::MaxValue)
PreferredLifetime : Infinite ([TimeSpan]::MaxValue)
SkipAsSource      : False
PolicyStore       : ActiveStore

```
In my case, the correct one is the second.

**Comment by bendem** [comment]
Using WSL2 on W10, I don't have the nat interface, not sure if it's W11 specific. According to [this](https://serverfault.com/a/974591/459873), it looks like it's a recent addition.

**Comment by michal5520pl** [comment]
Windows 11 22H2, packer version 1.8.3.

I have tried plugin version 1.0.1, 1.0.3, 1.0.4 and still does not work.

Output:
```
PS C:\VirtualMachines\HashiCorp> packer build .\packer.pkr.hcl
Warning: Hyper-V might fail to create a VM if there is not enough free memory in the system.

  on .\packer.pkr.hcl line 10:
  (source code not available)


Kubernetes master1.hyperv-iso.hyper-v: output will be in this color.

==> Kubernetes master1.hyperv-iso.hyper-v: Creating build directory...
==> Kubernetes master1.hyperv-iso.hyper-v: Retrieving ISO
==> Kubernetes master1.hyperv-iso.hyper-v: Trying file://C:\VirtualMachines\CentOS-Stream-9-latest-x86_64-dvd1.iso
==> Kubernetes master1.hyperv-iso.hyper-v: Trying file://C:/VirtualMachines/CentOS-Stream-9-latest-x86_64-dvd1.iso?checksum=sha256%3A4d7a446f5688a3efcfa0f056f22dd779d01f888df2ce4907098b656d568b626e
==> Kubernetes master1.hyperv-iso.hyper-v: file://C:/VirtualMachines/CentOS-Stream-9-latest-x86_64-dvd1.iso?checksum=sha256%3A4d7a446f5688a3efcfa0f056f22dd779d01f888df2ce4907098b656d568b626e => C:/VirtualMachines/CentOS-Stream-9-latest-x86_64-dvd1.iso
==> Kubernetes master1.hyperv-iso.hyper-v: Starting HTTP server on port 8388
==> Kubernetes master1.hyperv-iso.hyper-v: Creating switch 'Default Switch' if required...
==> Kubernetes master1.hyperv-iso.hyper-v:     switch 'Default Switch' already exists. Will not delete on cleanup...
==> Kubernetes master1.hyperv-iso.hyper-v: Creating virtual machine...
==> Kubernetes master1.hyperv-iso.hyper-v: Enabling Integration Service...
==> Kubernetes master1.hyperv-iso.hyper-v: Mounting os dvd drive C:/VirtualMachines/CentOS-Stream-9-latest-x86_64-dvd1.iso ...
==> Kubernetes master1.hyperv-iso.hyper-v: Skipping mounting Integration Services Setup Disk...
==> Kubernetes master1.hyperv-iso.hyper-v: Mounting secondary DVD images...
==> Kubernetes master1.hyperv-iso.hyper-v: Configuring vlan...
==> Kubernetes master1.hyperv-iso.hyper-v: Determine Host IP for HyperV machine...
==> Kubernetes master1.hyperv-iso.hyper-v: Error getting host adapter ip address: No ip address.
==> Kubernetes master1.hyperv-iso.hyper-v: Clean up os dvd drive...
==> Kubernetes master1.hyperv-iso.hyper-v: keep_registered set. Skipping unregister/deletion of VM.
==> Kubernetes master1.hyperv-iso.hyper-v: Deleting output directory...
==> Kubernetes master1.hyperv-iso.hyper-v: Deleting build directory...
==> Kubernetes master1.hyperv-iso.hyper-v: Error deleting build directory: remove C:\Users\Szczur\AppData\Local\Temp\hyperv3889741172\Kubernetes master1\Virtual Machines\362860FB-151B-4B73-8C85-59E25F3ABCD9.vmcx: The process cannot access the file because it is being used by another process.
Build 'Kubernetes master1.hyperv-iso.hyper-v' errored after 47 seconds 396 milliseconds: Error getting host adapter ip address: No ip address.

==> Wait completed after 47 seconds 396 milliseconds

==> Some builds didn't complete successfully and had errors:
--> Kubernetes master1.hyperv-iso.hyper-v: Error getting host adapter ip address: No ip address.

==> Builds finished but no artifacts were created.
PS C:\VirtualMachines\HashiCorp>
```

Log file:
```
2022/10/15 23:26:01 [INFO] Packer version: 1.8.3 [go1.17.11 windows amd64]
2022/10/15 23:26:01 [TRACE] discovering plugins in C:\HashiCorp
2022/10/15 23:26:01 [TRACE] discovering plugins in C:\Users\Szczur\AppData\Roaming\packer.d\plugins
2022/10/15 23:26:01 [DEBUG] Discovered plugin: hyperv = C:\Users\Szczur\AppData\Roaming\packer.d\plugins\github.com\hashicorp\hyperv\packer-plugin-hyperv_v1.0.1_x5.0_windows_amd64.exe
2022/10/15 23:26:01 [DEBUG] Discovered plugin: hyperv = C:\Users\Szczur\AppData\Roaming\packer.d\plugins\github.com\hashicorp\hyperv\packer-plugin-hyperv_v1.0.3_x5.0_windows_amd64.exe
2022/10/15 23:26:01 [DEBUG] Discovered plugin: hyperv = C:\Users\Szczur\AppData\Roaming\packer.d\plugins\github.com\hashicorp\hyperv\packer-plugin-hyperv_v1.0.4_x5.0_windows_amd64.exe
2022/10/15 23:26:01 [INFO] found external [iso vmcx] builders from hyperv plugin
2022/10/15 23:26:01 [TRACE] discovering plugins in .
2022/10/15 23:26:01 [INFO] PACKER_CONFIG env var not set; checking the default config file path
2022/10/15 23:26:01 [INFO] PACKER_CONFIG env var set; attempting to open config file: C:\Users\Szczur\AppData\Roaming\packer.config
2022/10/15 23:26:01 [WARN] Config file doesn't exist: C:\Users\Szczur\AppData\Roaming\packer.config
2022/10/15 23:26:01 [INFO] Setting cache directory: C:\VirtualMachines\HashiCorp\packer_cache
e: cannot determine if process is in background: Process background check error: not implemented yet
2022/10/15 23:26:01 machine readable: version []string{"1.8.3"}
2022/10/15 23:26:01 machine readable: version-prelease []string{""}
2022/10/15 23:26:01 machine readable: version-commit []string{"38b47d8211fe16ea58137317c4b3d719710a6df3"}
2022/10/15 23:26:01 ui: Packer v1.8.3
2022/10/15 23:26:01 [INFO] (telemetry) Finalizing.
2022/10/15 23:26:02 waiting for all plugin processes to complete...
```

packer.pkr.hcl file:
```
packer {
    required_plugins {
        hyperv = {
            version = ">= 1.0.4"
            source = "github.com/hashicorp/hyperv"
        }
    }
}

source "hyperv-iso" "hyper-v" {
    iso_checksum = "sha256:4d7a446f5688a3efcfa0f056f22dd779d01f888df2ce4907098b656d568b626e"
    iso_url = "file://C:\\VirtualMachines\\CentOS-Stream-9-latest-x86_64-dvd1.iso"
    output_directory = "C:\\VirtualMachines\\Hyper-V\\Kubernetes-master1"
    disk_size = 21000
    disk_block_size = 1
    vm_name = "Kubernetes master1"
    switch_name = "Default Switch"
    mac_address = "0000deadbeef"
    cpus = 2
    enable_dynamic_memory = true
    keep_registered = true
    http_directory = "./"

    ssh_username = "root"

    shutdown_command = "shutdown now"

    boot_wait = "20s"
    boot_command = [
        "<up><tab>",
        " ip=dhcp init.ks={{ .HTTPIP }}:{{ .HTTPPort }}/centos_str9.ks",
        "<enter>"
    ]
}

build {
    name = "Kubernetes master1"

    sources = [ "sources.hyperv-iso.hyper-v" ]
}
```
I have Default Switch in Windows, tried also "vSwitch (Default Switch)" and "vEthernet (Default Switch)". External virtual switches are not a way for me.

I appreciate any help, thank you

**Comment by fsdrw08** [comment]
any update for this issue? I got same error in both packer 1.7.10 and 1.8.5

**Comment by fsdrw08** [comment]
ok, I find that this [commit](https://github.com/hashicorp/packer-plugin-hyperv/commit/c4fd17d3cd6ca4713ab786df26a863da7cc12d08) fixed this issue, but the plugin with this commit had not release yet.  
To fix it manually, I had to clone the main branch of this repo, and build a temporary plugin bin file by running `go build`, and put the bin file into my working dir, comment out the packer required_plugins block, the run packer build, then the issue gone.

**Comment by mcharo** [comment]
As @fsdrw08 said, this is fixed in `main` (at least for Windows 11, where I built and tested). What is required for a new release to be generated and published?

**Comment by brewsteropsdev** [comment]
Second this ^ would be nice to get a new release out so a manual build isn't required. @lbajolet-hashicorp can you help facilitate this?

**Comment by michaelpayne02** [comment]
@fsdrw08 I followed your exact steps and am still getting the error.
Packer v1.8.5  (via chocolatey)
Hyperv Plugin built from commit e162a34 placed in the CWD
Windows 11 22H2

**Comment by fsdrw08** [comment]
@nywilken 
Would you please release a new version for this plugin to fix this bug? I saw that you had push a commit to fix this bug months ago

> ok, I find that this [commit](https://github.com/hashicorp/packer-plugin-hyperv/commit/c4fd17d3cd6ca4713ab786df26a863da7cc12d08) fixed this issue, but the plugin with this commit had not release yet. To fix it manually, I had to clone the main branch of this repo, and build a temporary plugin bin file by running `go build`, and put the bin file into my working dir, comment out the packer required_plugins block, the run packer build, then the issue gone.

**Comment by nywilken** [comment]
The change mentioned within this issue has been applied and released in v1.1.0 of the Hyperv plugin. Are folks still having issues here?

**Comment by nywilken** [comment]
I think it might be safe to close. But if I am wrong please drop a comment and I will reopen and work to figure out what might be happening here. 

FWIW I took a similar approach to what is outline below before running my Packer build. 

So better first construct a virtual switch in Hyper-V for working with Packer. Follow these steps:

1. Open the Hyper-V Manager console and click on the Virtual Switch Manager option in the Actions pane.
1. Select the External option, and then click on Create Virtual Switch.
1. Name your virtual switch 'Wi-Fi' and select the physical network adapter that will be used for the external network.

Click on OK to create the virtual switch.

**Comment by psipika** [comment]
> To provision a Hyper-V VM with Packer there needs to be an **External Virtual Switch**, Packer only creates an **Internal Virtual Switch**.
> 
> I have this in my Packer template.
> 
> ```terraform
> switch_name          = "Wi-Fi"
> ```
> 
> In the Hyper-V manager I could do two relevant things to this switch in the `Virtual Switch Manager`:
> 
> 1. Change the **Connection Type** to External network.
> 2. Select the **real Wi-Fi** adapter in my laptop.
> 
> By default the virtual switch was connected to the external network with the (unplugged) ethernet adapter.
> 
> Such a simple thing! Works on Windows 10 and 11, with Packer 1.8.1 and Hyper-V plugin 1.0.4.
> 
> So better first construct a virtual switch in Hyper-V for working with Packer. Follow these steps:
> 
> 1. Open the Hyper-V Manager console and click on the Virtual Switch Manager option in the Actions pane.
> 2. Select the External option, and then click on Create Virtual Switch.
> 3. Name your virtual switch 'Wi-Fi' and select the physical network adapter that will be used for the external network.
> 
> Click on OK to create the virtual switch.

This actually did not work for me on Windows 10, packer 1.8.6 and Hyper-V plugin 1.1.3 when deploying a Ubuntu 22.04 LTS VM. Regardless of which switch I used (an External one, or the Default Switch), I had to install the packages listed as part of [this stackoverflow exchange](https://stackoverflow.com/questions/33027204/how-can-i-get-hyper-v-to-detect-my-ubuntu-vms-ip-address).

**Comment by emaayan** [comment]
> > To provision a Hyper-V VM with Packer there needs to be an **External Virtual Switch**, Packer only creates an **Internal Virtual Switch**.
> > I have this in my Packer template.
> > ```hcl
> > switch_name          = "Wi-Fi"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > In the Hyper-V manager I could do two relevant things to this switch in the `Virtual Switch Manager`:
> > 
> > 1. Change the **Connection Type** to External network.
> > 2. Select the **real Wi-Fi** adapter in my laptop.
> > 
> > By default the virtual switch was connected to the external network with the (unplugged) ethernet adapter.
> > Such a simple thing! Works on Windows 10 and 11, with Packer 1.8.1 and Hyper-V plugin 1.0.4.
> > So better first construct a virtual switch in Hyper-V for working with Packer. Follow these steps:
> > 
> > 1. Open the Hyper-V Manager console and click on the Virtual Switch Manager option in the Actions pane.
> > 2. Select the External option, and then click on Create Virtual Switch.
> > 3. Name your virtual switch 'Wi-Fi' and select the physical network adapter that will be used for the external network.
> > 
> > Click on OK to create the virtual switch.
> 
> This actually did not work for me on Windows 10, packer 1.8.6 and Hyper-V plugin 1.1.3 when deploying a Ubuntu 22.04 LTS VM. Regardless of which switch I used (an External one, or the Default Switch), I had to install the packages listed as part of [this stackoverflow exchange](https://stackoverflow.com/questions/33027204/how-can-i-get-hyper-v-to-detect-my-ubuntu-vms-ip-address).

the page was removed, how did you solve it?

**Comment by zoredache** [comment]
[emaayan](https://github.com/emaayan)

> the page was removed, how did you solve it?

That page is about getting Ubuntu to correctly report the IP to the hypervisor. It wanted you to install some variation of the package of `linux-cloud-tools*` the exact details seemed to depend on the release and kernel version.

Here is an archive of that page.  https://imgur.com/a/FUPrNXy

On Debian I think you need to install `hyperv-daemons` to get the system to report the IP to the host properly.

**Comment by emaayan** [comment]
yea i found out you don't need to mark vlan when using windows 11 hyper-v
